version: '2'

services:

  php:
    build:
      dockerfile: Dockerfile
      context: build/php
    depends_on:
      - db
      - memcached
      - gearman
    environment:
      - DB_ENV_MYSQL_USER=root
      - DB_ENV_MYSQL_DATABASE=console
      - DB_ENV_MYSQL_PASSWORD=root
      - DB_ENV_MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./yii:/app/yii
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./web:/app/web
      - ./src:/app/src
      - ./docs:/app/docs
      - ./vendor:/app/vendor
      - ./runtime:/app/runtime

  nginx:
    image: cornernote/nginx:1.13
    environment:
      - DH_SIZE=512
    volumes:
      - dhparam:/etc/nginx/dhparam
      - ./build/nginx/config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/app/web
      - ./src:/app/src
      - ./vendor:/app/vendor
      - ./runtime:/app/runtime
    depends_on:
      - php

  db:
    image: percona:5.5
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - MYSQL_USER=root
      - MYSQL_DATABASE=console
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
      - binlog:/var/log/mysql

  memcached:
    image: memcached

  gearman:
    image: kendu/gearman

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    volumes:
      - /sessions
    depends_on:
      - db


volumes:
  mysql:
  binlog:
  dhparam:

